# Generated by Django 5.2 on 2025-04-29 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.jobpost",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("candidate", "job")},
        ),
    ]
