# Generated by Django 5.2 on 2025-05-01 12:18

import candidates.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="linkedin_profile",
            field=candidates.models.OptionalURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="portfolio_url",
            field=candidates.models.OptionalURLField(blank=True, null=True),
        ),
    ]
