# Generated by Django 5.2 on 2025-05-09 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="category",
        ),
        migrations.RenameField(
            model_name="jobpost",
            old_name="company_name",
            new_name="company",
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="responsibilities",
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="salary_max",
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="salary_min",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="salary",
            field=models.CharField(default="Not specified", max_length=100),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="slug",
            field=models.SlugField(default="", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("FT", "Full Time"),
                    ("PT", "Part Time"),
                    ("CT", "Contract"),
                    ("IN", "Internship"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="expiry_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="posted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="status",
            field=models.CharField(
                choices=[("OP", "Open"), ("CL", "Closed"), ("DR", "Draft")],
                default="OP",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.FileField(upload_to="resumes/")),
                ("cover_letter", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("R", "Reviewed"),
                            ("A", "Accepted"),
                            ("R", "Rejected"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.jobpost"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jobs.location"
            ),
        ),
        migrations.DeleteModel(
            name="JobCategory",
        ),
        migrations.DeleteModel(
            name="JobLocation",
        ),
    ]
